development:
  dialect: "mysql"
  database: "budayaid_backend_sql_development"
  host: "localhost"
  port: "3306"
  user: "username"
  password: "password"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://username:password@(localhost:3306)/budayaid_backend_sql_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://username:password@(localhost:3306)/budayaid_backend_sql_production?parseTime=true&multiStatements=true&readTimeout=1s"}}